version: '3.7'
services:
  kamailio:
    container_name: kamailio
    build:
      context: ./build_kam
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      rtpengine:
        condition: service_healthy
    environment:
      - DOMINIO_BASE=meuvoip.com.br
      - KAMAILIO_IP_INTERNO=192.168.5.12 ## container ip
      - KAMAILIO_IP_EXTERNO=177.177.177.177 ## local ip
      - KAMAILIO_IP_DB=172.25.0.21 ## postgres ip
      - RTPENGINE_IP=192.168.5.12 ## rtpengine ip
      - POSTGRES_USER=postgres ## db root
      - POSTGRES_PASSWORD=58e1bab9f6613cce680ed55245a91d30 ## db root pass
      - DB_NAME=kamailio
      - SELFSIGNED=true
    #entrypoint: "sleep 1000000"
    network_mode: host
    logging:
      options:
        max-size: 100M

  postgres:
    container_name: postgres
    image: postgres:13.12-alpine
    restart: always
    healthcheck:
      test: pg_isready -d postgres -h localhost -p 5432 -U postgres
    expose:
      - 5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres 
      - POSTGRES_USER=postgres ## db root
      - POSTGRES_PASSWORD=58e1bab9f6613cce680ed55245a91d30 ## db root pass
    networks:
      net:
        ipv4_address: 172.25.0.21
    logging:
      options:
        max-size: 100M

  rtpengine:
    container_name: rtpengine
    build:
      context: ./build_rtp
      dockerfile: ./Dockerfile
    restart: always
    privileged: true
    healthcheck:
      test: curl --fail http://192.168.5.12:2225/ping || exit 1 ## internal ip + ng-port
    environment:
      - IPINTERNO=192.168.5.12 ## internal ip
      - IPEXTERNO=177.177.177.177 ## external ip
      - PORT_MIN=10000
      - PORT_MAX=20000
    #entrypoint: sleep 1000000
    network_mode: host
    logging:
      options:
        max-size: 100M

  asterisk:
    container_name: asterisk
    build:
      context: ./build_ast
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - DOMINIO_BASE=meuvoip.com.br
      - IPINTERNO=192.168.5.12 ## internal ip
      - PORT_MIN=18000
      - PORT_MAX=18100
    volumes:
      #- ./conf:/etc/asterisk
      - ./static-http:/var/lib/asterisk/static-http
    network_mode: host          
    logging:
      options:
        max-size: 100M

networks:
  net:
    external: true